### PR TITLE
add YKUSHXS model

### PR DESCRIPTION
**Pull request by albersaber**

### CODE REVIEW

**Comment by cladmi** [comment]
I wanted to look at this as I am also interested but currently you changed all the spacing to tabs. So I cannot really review.
Also I think will not be merged like this as changing the whitespace format would be a coding style change.

**Comment by cladmi** [comment]
I however tested the change and it is indeed working with my new `ykushxs`.

**Comment by cladmi** [comment]
Some remarks on the code (when replacing the tabs by spaces).

There is a typo `self._proudct_id` instead of `_product_id`.

There are some checks done on `_product_id` when they can only be done on `ykush.get_downstream_port_count` as it is only about changing the text.
Also if it is saying "ports" and only showing one it would not be that dramatic I think :)

For the implementation around, I would maybe more currently hack more inside the class and maybe return a fake firmware version and so make the `YKUSH` class coherent from outside.

**Comment by yep1** [comment]
Hi albersaber and cladmi,
thanks for your contributions adding support for YKUSH XS and testing it. Your changes have been merged with master branch and committed.
Best Regards.

**Pull request merged**
